### ISSUE TITLE
Update Mapbox PeerDependency

### ISSUE THREAD

**Issue by sroettering** [mapbox/mapbox-gl-language#14]
Are there any plans on updating the mapbox-gl dependency?
I would like to use this plugin in my application, but mapbox-gl 0.29.0 is too old for my needs.

**Comment by andrewharvey** [comment]
@sroettering I'm using this with mapbox-gl 0.48.0 and haven't run into any issues. the Peer dependency just says you need 0.29.0 or higher right?

**Comment by damienalexandre** [comment]
Yes, it works with newer versions of MapboxGL. 
But it's disturbing to see errors and warning when using Yarn:

```
$ yarn check

yarn check v1.12.3
error "@mapbox/mapbox-gl-language#mapbox-gl@^0.29.0" doesn't satisfy found match of "mapbox-gl@0.51.0"
```

Is that a yarn or mapbox issue?

**Comment by ryanhamley** [comment]
I'm closing this as wont-fix. Unless there's a really compelling reason to do so, I don't want to exclude any older versions and potentially break legacy maps deployed somewhere.
