### ISSUE TITLE
Release an up-to-date version (on NPM)

### ISSUE THREAD

**Issue by sjockers** [mapbox/mapbox-gl-language#24]
Hey, we love this package and would like to install it via the NPM registry, but the [last release (0.9.2)](https://www.npmjs.com/package/@mapbox/mapbox-gl-language) is 10 months old and lacks features that have been merged into the master branch since. 

Are you planning on releasing this some time soon? Is there anything I could help with?

**Comment by andrewharvey** [comment]
v0.10.0 has been released which is current as of now https://github.com/mapbox/mapbox-gl-language/releases
