### ISSUE TITLE
When the style of the map changes, the map is always translated in "English".

### ISSUE THREAD

**Issue by mike7515** [mapbox/mapbox-gl-language#26]
Trying to change the map style from _"mapbox://mapbox-streets-v10"_ to _"mapbox://mapbox-satellite-streets-v9"_, but when map.setStyle is called, the map is translated to "English" .

I suppose that the library needs to update the style with the true language, because if I remove this line of code "this._map.off ('styledata', this._initialStyleUpdate);" the _initialStyleUpdate method is called from the library and the map is translated correctly.

Thanks

**Comment by coocy** [comment]
I have forked and made an improved version.
Changing the map's style won't reset the language.
Please check this https://github.com/coocy/mapbox-gl-language/
Demo: http://coocy.github.io/mapbox-gl-language/example/

**Comment by andrewharvey** [comment]
@coocy that's great, are you interested in putting together a PR? I can help review it.
