### ISSUE TITLE
README.md Supported Styles

### ISSUE THREAD

**Issue by xuekai-china** [mapbox/mapbox-gl-language#29]
mapbox://mapbox-streets-v10
mapbox://mapbox-outdoors-v10
mapbox://mapbox-dark-v9
mapbox://mapbox-light-v9
mapbox://mapbox-satellite-streets-v9
mapbox://mapbox-traffic-day-v2
mapbox://mapbox-traffic-night-v2

It should be changed to

mapbox://styles/mapbox-streets-v10
mapbox://styles/mapbox-outdoors-v10
mapbox://styles/mapbox-dark-v9
mapbox://styles/mapbox-light-v9
mapbox://styles/mapbox-satellite-streets-v9
mapbox://styles/mapbox-traffic-day-v2
mapbox://styles/mapbox-traffic-night-v2

**Comment by wanghongrui** [comment]
mapbox://styles/mapbox/streets-v10
mapbox://styles/mapbox/outdoors-v10
mapbox://styles/mapbox/dark-v9
mapbox://styles/mapbox/light-v9
mapbox://styles/mapbox/satellite-streets-v9
mapbox://styles/mapbox/traffic-day-v2
mapbox://styles/mapbox/traffic-night-v2

**Comment by ryanhamley** [comment]
Closing as outdated
