### ISSUE TITLE
Support of streets-v11 (and other styles based on Streets v8 vector tile source)

### ISSUE THREAD

**Issue by ellogram** [mapbox/mapbox-gl-language#31]
The plugin does not seem to work with the latest mapbox styles (streets-v11, dark-v10 and bright-v10 for instance), derived from the Streets v8 vector tile source.

Here is a fiddle with the example from the [mapbox blog article introducing the plugin](https://blog.mapbox.com/how-to-localize-your-maps-in-mapbox-gl-js-da4cc6749f47), adapted so it uses the latest versions of the plugin, mapbox GL JS and the streets-v11 style:
[https://jsfiddle.net/yo1grbdx/3/](https://jsfiddle.net/yo1grbdx/3/)
The automatic switch of the map language does not work, but it works if we use the streets-v10 style. We can also still change the language of a layer directly if we use setLayoutProperty.

I have looked a bit into the code of the plugin, and the main problem seems to be that the "languageFieldName" is no longer expected to be a string (like "{name_fr}"), but rather an array (i.e. an expression, like ["get", "name_fr"], cf. #20). There are also changes in the source layer names and layer ids.

Is the support of the new styles planned in the near future?
Thank you.

**Comment by andrewharvey** [comment]
Yes, I believe this is #20.

**Comment by gideonvd** [comment]
For now, you can use :
`map.setLayoutProperty('country-label', 'text-field', ['get', 'name_' + language]);`

See:
https://docs.mapbox.com/mapbox-gl-js/example/language-switch/

**Comment by ellogram** [comment]
Thank you.
This is what I did for now to change all the labels on the map:
```
const labelList = map.getStyle().layers.filter(layer => {
  return /-label/.test(layer.id);
});
for (let labelLayer of labelList) {
  map.setLayoutProperty(labelLayer.id, 'text-field', ['coalesce', ['get', 'name_' + language], ['get', 'name']]);
}
```

**Comment by bravecow** [comment]
https://github.com/bravecow/mapbox-gl-controls/blob/master/src/language/language.js#L89-L107

I handle string as single case and other as JSON with regex replace. Notice that only first language property in `coalesce ` should be replaced. Fallback property should always be `{name}`.

I would like to make a PR, but my previous PR was without response for month. So I reinvented the wheel. With ES6 and dynamic language switching (e.g. for SPA).

**Comment by bravecow** [comment]
@elifitch almost 🙂 
you can loose this layers:

![image](https://user-images.githubusercontent.com/988471/63176148-11cadb80-c04e-11e9-83ec-10c5c5974d8c.png)

![image](https://user-images.githubusercontent.com/988471/63176240-43dc3d80-c04e-11e9-9747-877664c42421.png)

![image](https://user-images.githubusercontent.com/988471/63176304-59e9fe00-c04e-11e9-985d-abe062b89664.png)

And so on. So some fields besides just `get` contains some logic or different property (as house number).

**Comment by snkashis** [comment]
@asheemmamoowala is one of these user-contributed solutions going to be put into a release soon?

**Comment by asheemmamoowala** [comment]
@snkashis This is not currently on our roadmap to fix. We'd be happy to accept a PR for it though.

**Comment by coocy** [comment]
I have forked and made an improved version.
It works with Mapbox Streets v7 & v8 vector tile styles.
Please check this https://github.com/coocy/mapbox-gl-language/
Demo: http://coocy.github.io/mapbox-gl-language/example/

**Comment by andrewharvey** [comment]
@coocy that's great, are you interested in putting together a PR? I can help review it.

**Comment by janeschindler** [comment]
Thanks for developing this issue. I tried installing the mapbox-gl-language plugin, but I assume I ran into the problem with the v7 tiles. I'm using the easy workaround https://github.com/mapbox/mapbox-gl-language/issues/31#issuecomment-510307581 for now.

**Comment by fdagostino** [comment]
+1
