### ISSUE TITLE
How to translate map to Portuguese of Brazil?

### ISSUE THREAD

**Issue by renantheodoro** [mapbox/mapbox-gl-language#33]
Hi, I have an issue about the translation of the map. I want to translate to PT-BR language, but the options only gives the Portuguese of Portugal. How could I resolve this? There is some other information that I have missed?

Thank you, by the way!

**Comment by kkaefer** [comment]
This plugin relies on the data provided by your vector tile source. The vector tiles offered by Mapbox currently only support Portugese as spoken in Portugal.
