### ISSUE TITLE
 map.addControl is not a function

### ISSUE THREAD

**Issue by Roxannej** [mapbox/mapbox-gl-language#37]
showModal() {
      // 英文标注转换为中文
      this.mapVisible = true;
      // 在v-if下获取的this.$refs是空的
      this.$nextTick(() => {
        // console.log("--------", this.$refs);
        // console.log("--------", this.$refs.id);
        // let mymap = this.$refs.id;
        let mymap = this.elements.t1.id;
        mapboxgl.accessToken =
          'pk.eyJ1Ijoicm94YW5uZWYyIiwiYSI6ImNrZW1qcXU1MjIyaDUycm83enQ3aTl5YWwifQ.RVn2aTnGRCk3xtOozCtyaA';
        // mapboxgl.setRTLTextPlugin(
        //   'https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.1.0/mapbox-gl-rtl-text.js',
        //   null,
        //   true // Lazy load the plugin
        // );
        this.map = new mapboxgl.Map({
          container: mymap, // container id
          style: 'mapbox://styles/mapbox/streets-v11', // style URL
          center: [121.50109, 31.23691], // starting position [lng, lat]
          zoom: 9, // starting zoom
        });
        // 设置语言
        var language = new MapboxLanguage();
        map.addControl(language);
        // const language = new MapboxLanguage({ defaultLanguage: 'zh' });
        // map.addControl(language);
        // // 全图
        // map.addControl(new mapboxgl.FullscreenControl());
        // // 定位
        // new mapboxgl.GeolocateControl({
        //   positionOptions: {
        //     enableHighAccuracy: true,
        //   },
        //   trackUserLocation: true,
        // });
      });
    },

**Comment by andrewharvey** [comment]
looks like you've set the `new mapboxgl.Map` into `this.map` but later referring to just `map`, which aren't the same reference, so this is an issue in your code.
