### ISSUE TITLE
How to use this with mapbox-leaflet-gl-js?

### ISSUE THREAD

**Issue by fschutt** [mapbox/mapbox-gl-language#40]
I use Leaflet to control the map while using mapbox-leaflet-gl-js to render the vector tiles to leaflet.

How do I enable this plugin? My code so far is:

```js
"use strict";

var map = L.map('mapid', {
    center: [DEFAULT_LAT, DEFAULT_LNG],
    format: 'jpg80',
    zoom: DEFAULT_ZOOMLEVEL,
    minZoom: 2,
    maxZoom: 14,
    attributionControl: false,
    preferCanvas: true,
    reuseTiles: true,
    unloadInvisibleTiles: false,
    maxBoundsViscosity: 1.0,
    continuousWorld: false,
    worldCopyJump: true,
    noWrap: true,
});

var gl = L.mapboxGL({
    accessToken: L.mapbox.accessToken,
    style: 'mapbox://styles/mapbox/outdoors-v11'
}).addTo(map);

map.zoomControl.setPosition('topright'); 

// ... etc.
```

But since I am using `L.map` instead of the raw `mapboxgl.map` - how do I enable this plugin? Thanks.

**Comment by ryanhamley** [comment]
I'm not sure this is supported by mapbox-gl-leaflet. The point of that library is to allow developers to add vector tiles to Leaflet. You can access the GL map with `gl.getMapboxMap()` but I don't know if that allows you to add a control. mapbox-gl-leaflet is experimental and not actively maintained so I'm not familiar with its usage. If you still need help with this, I'd recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us).
