### ISSUE TITLE
CDN version is outdated

### ISSUE THREAD

**Issue by adddz** [mapbox/mapbox-gl-language#47]
Hi there,

I was wondering why the examples weren't working locally, then I've realized that the CDN version is outdated for some reasons. The code in the `index.js` (https://github.com/mapbox/mapbox-gl-language/blob/master/index.js) is different than the CDN version (https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-language/v0.10.1/mapbox-gl-language.js), for example it has more supported languages and it works.

Could you please update it, please?

**Comment by lucasfrey** [comment]
Up, I would like to have this updated as well :)

**Comment by ryanhamley** [comment]
This is fixed. v1.0.0, tagged to the latest commit on master, has been released on npm and the cdn
