### ISSUE TITLE
Update peer dependency for new mapbox-gl version

### ISSUE THREAD

**Issue by tdn** [mapbox/mapbox-gl-language#48]
Peer dependencies break `npm install` when working with the newest verison of mapbox-gl.

```
"peerDependencies": {
        "mapbox-gl": ">=0.29.0 <2.0.0"
      }
```

Should be updated to

```
"peerDependencies": {
        "mapbox-gl": ">=0.29.0 <=2.2.0"
      }
```

**Comment by andrewharvey** [comment]
#42 solves this, but it's yet to me merged and released

**Comment by ryanhamley** [comment]
Fixed. v1.0.0 is released on npm and cdn
