### ISSUE TITLE
Simplified Chinese

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-language#5]
This plugin currently omits `zh-Hans` from [the list of supported languages](https://github.com/mapbox/mapbox-gl-language/blob/d97c3fbb44b7ac679fb679264ca94186af5d3cea/index.js#L35). Judging from [the Mapbox Streets v7 documentation](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#overview), `name_zh-Hans` would probably be more appropriate than `name_zh` when the browser’s preferred language is `zh-Hans`, `zh-CN`, or `zh-Hans-CN`.

For mapbox/mapbox-gl-native#9063, I relied on the locale matching functionality built into iOS and macOS, but I don’t think there’s an analogue on the Web, so `zh-Hans` would need a special case or two.

/cc @lukasmartinelli

**Comment by 1ec5** [comment]
> For mapbox/mapbox-gl-native#9063, I relied on the locale matching functionality built into iOS and macOS, but I don’t think there’s an analogue on the Web, so `zh-Hans` would need a special case or two.

Totally forgot that [locale-utils](https://github.com/mapbox/locale-utils/) exists for this very purpose.

/cc @bsudekum

**Comment by andrewharvey** [comment]
In [Mapbox Streets v8](https://www.mapbox.com/vector-tiles/mapbox-streets-v8/#common-fields) this changed to `zh-Hans` for Simplified Chinese and `zh-Hant` for Traditional Chinese (if available, but may contain some Simplified Chinese).

**Comment by ryanhamley** [comment]
Solved by #39
