### ISSUE TITLE
cannot translate the whole map to Chinese

### ISSUE THREAD

**Issue by lance0109** [mapbox/mapbox-gl-language#50]
![image](https://user-images.githubusercontent.com/18597252/133359362-24dccd14-ee69-487e-82ef-8d1393f823b4.png)

version:
"@mapbox/mapbox-gl-language": "^1.0.0",
"mapbox-gl": "^2.4.0"

styles:
'mapbox://styles/mapbox/light-v10'

``` js
this.mapInstance = this.swiperIdx.map((idx) => {
       const mapDom = document.querySelector(
              `${BASE_MAP_CLASS}${idx}`
       );

       return new mapboxgl.Map({
               container: mapDom,
               style: MAP_STYLE_LIGHT,
               minZoom: 1,
               zoom: 2,
       });
});

mapboxgl.setRTLTextPlugin(
        'https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.3/mapbox-gl-rtl-text.js'
);

this.mapInstance.map((map) => {
        map.addControl(new mapboxgl.NavigationControl(), 'top-right');

        map.addControl(
                new MapboxLanguage({
                       defaultLanguage: 'zh-Hans',
                })
        );
});
```

When set the language to 'zh-Hans', just translate China & Japan to Chinese, not whole world.

**Comment by devgioele** [comment]
I have a similar issue, where labels of South Tyrol are not translated

**Comment by teenageknight** [comment]
This might not be your issue, but i had a similar issue and mine was becuase the map style i was using was not supported correctly. If you want to check, use `mapbox://styles/mapbox/streets-v11` as your style to test

**Comment by teenageknight** [comment]
When you get a style that is based on v8 but is a custom style, it doesnt actually error out, it just localizes all the languages based on their local areas (ie china is in chinese, iran is arabic, etc etc). Try it with a default style

**Comment by lance0109** [comment]
it works fine in live server. close the ticket.
